Repository Garis-Kode/festiris-be, pull requests merged in 2024-09, with the labels that each got.

#2 1 set up the initial backend project
  .gitignore
  README.md
  app/Helpers/Response.php
  app/Helpers/Router.php
  app/Models/User.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/auth.php
  config/passport.php
  database/migrations/2024_09_15_074404_create_oauth_auth_codes_table.php
  database/migrations/2024_09_15_074405_create_oauth_access_tokens_table.php
  database/migrations/2024_09_15_074406_create_oauth_refresh_tokens_table.php
  database/migrations/2024_09_15_074407_create_oauth_clients_table.php
  database/migrations/2024_09_15_074408_create_oauth_personal_access_clients_table.php
  routes/api.php
Labels: enhancement

#6 refac: change design pattern to service repository pattern
  .gitignore
  app/Http/Controllers/Api/Auth/AuthController.php
  app/Interfaces/AuthInterface.php
  app/Models/User.php
  app/Repositories/AuthRepository.php
  app/Repositories/User/UserRepository.php
  app/Repositories/User/UserRepositoryImplement.php
  app/Services/Auth/AuthService.php
  app/Services/Auth/AuthServiceImplement.php
  app/Traits/MapFields.php
  composer.json
  composer.lock
  config/easy-repository.php
  database/migrations/0001_01_01_000000_create_users_table.php
  routes/api.php
  routes/api/v1/Auth/auth.php
Labels: duplicate

#10 Implement user login api
  .docker/nginx/default.conf
  .docker/php/local.ini
  Dockerfile
  app/Exceptions/BadRequestException.php
  app/Exceptions/UnauthorizedException.php
  app/Exceptions/UnexpectedErrorException.php
  app/Helpers/Response.php
  app/Helpers/Router.php
  app/Http/Controllers/Api/Auth/AuthController.php
  app/Http/Middleware/OnlyAcceptJson.php
  app/Http/Requests/Auth/RegistrationRequest.php
  app/Http/Requests/LoginRequest.php
  app/Http/Requests/RefreshTokenRequest.php
  app/Http/Resources/AuthTokenResource.php
  app/Http/Resources/UserResource.php
  app/Models/User.php
  app/Repositories/User/UserRepository.php
  app/Repositories/User/UserRepositoryImplement.php
  app/Services/Auth/AuthService.php
  app/Services/Auth/AuthServiceImplement.php
  bootstrap/app.php
  composer.json
  composer.lock
  config/easy-repository.php
  config/passport.php
  docker-compose.yml
  routes/api.php
  routes/api/v1/Auth/auth.php
  routes/web.php
Labels: testing, reviewing
